# General settings
general:
  seed: 2012
  classification: True
  train: True
  dataset: "libribrain"
  data_path: "./data/libribrain/"
  save_path: null

# Data hyperparameters
data:
  normalize: False

# Model hyperparameters
model:
  root_width_size: 48
  root_depth: 1
  root_activation: "relu"
  root_final_activation: null
  root_output_dim: 39
  positional_encoding: [12, 10]
  # positional_encoding: null
  init_state_layers: 1
  input_prev_data: False
  # conv_embedding: [64, 250, 0]
  conv_embedding: null
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: False
  forcing_prob: 0.25
  noise_theta_init: null
  std_lower_bound: 1.0e-4

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-4
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-0
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference hyperparameters
training:
  nb_epochs: 1000
  batch_size: 2048
  autoregressive: False
  print_every: 10
  save_every: 10
  valid_every: 10
  # val_criterion: "f1_score"
  val_criterion: "cce"
  smooth_inference: True
  nb_recons_loss_steps: null
  use_nll_loss: False
  inference_start: 100
  stochastic: False
