# General settings
general:
  seed: 2024
  train: True
  classification: False
  dataset: "celeba"
  data_path: "./data/"
  save_path: null

# Data hyperparameters
data:
  resolution: [64, 64]
  normalize: False
  positional_encoding: [10, 10]

# Model hyperparameters
model:
  root_width_size: 12
  root_depth: 5
  root_activation: "relu"
  root_final_activation: "tanh"
  init_state_layers: 2
  input_prev_data: False
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: True
  forcing_prob: 0.15
  noise_theta_init: null
  std_lower_bound: 1.0e-4

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-5
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference configurations
training:
  nb_epochs: 150
  batch_size: 512
  print_every: 10
  save_every: 10
  valid_every: 10
  val_criterion: "mse"
  autoregressive: True
  stochastic: False
  nb_recons_loss_steps: null
  use_nll_loss: True
  inference_start: 600
  smooth_inference: True
