# Base configuration file

# General settings
general:
  seed: 2024
  train: True
  classification: False
  dataset: "celeba"  # Options: mnist, cifar, lorentz, dynamics
  data_path: "./data/"
  # save_path: "./runs/250404-175026-Test/"
  save_path: null

# Data hyperparameters (dependent on the dataset)
data:
  downsample_factor: 1
  resolution: [32, 32]         # For celebA
  traj_length: 1000
  normalize: False

# Model hyperparameters
model:
  root_width_size: 24
  root_depth: 3
  root_activation: "relu"
  root_final_activation: 1.0
  init_state_layers: null
  input_prev_data: False
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: False
  forcing_prob: 0.15
  noise_theta_init: null
  std_lower_bound: 1.0e-4

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-5
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference hyperparameters
training:
  nb_epochs: 250
  batch_size: 1256
  print_every: 10
  save_every: 10
  valid_every: 10
  val_criterion: "mse"
  autoregressive: True
  stochastic: False
  nb_recons_loss_steps: null
  use_nll_loss: True
  inference_start: 600
