# Base configuration file

# General settings
general:
  seed: 2024
  classification: False
  train: True
  dataset: "electricity"  # Options: mnist, cifar, lorentz, dynamics
  data_path: "./data/dynamics/electricity/m2/"
  save_path: null

# Data hyperparameters (dependent on the dataset)
data:
  downsample_factor: 1
  resolution: [32, 32]         # For celebA
  traj_length: 1000
  normalize: True

# Model hyperparameters
model:
  root_width_size: 148
  root_depth: 1
  root_activation: "relu"
  root_final_activation: 1.0
  input_prev_data: False
  model_type: "gru"
  init_state_layers: 2          ## null to directly learn the initial state
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: True
  forcing_prob: 0.25
  noise_theta_init: null
  std_lower_bound: 1.0e-4
  rnn_hidden_size: 920          # For GRUs and LSTMs

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-4
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 10

# Training/Inference hyperparameters
training:
  nb_epochs: 100
  batch_size: 1400
  print_every: 10
  autoregressive: True
  checkpoint_every: 10
  nb_recons_loss_steps: null
  use_nll_loss: False
  inference_start: 96
