# Base configuration file

# General settings
general:
  seed: 2028
  classification: True
  train: True
  dataset: "spirals"  # Options: mnist, cifar, lorentz, dynamics
  data_path: "./data/spirals/"
  save_path: null

# Data hyperparameters (dependent on the dataset)
data:
  downsample_factor: 1
  resolution: [32, 32]         # For celebA
  traj_length: 1000

# Model hyperparameters
model:
  root_width_size: 24
  root_depth: 3
  root_activation: "swish"
  root_final_activation: null
  init_state_layers: 2      ## null to directly learn the initial state
  input_prev_data: False
  model_type: "lstm"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: False
  forcing_prob: 1.0
  noise_theta_init: null
  std_lower_bound: 1.0e-4
  rnn_hidden_size: 64   ## 900

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-5
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference hyperparameters
training:
  nb_epochs: 1000
  batch_size: 200      ## up to 10000
  autoregressive: False
  stochastic: False
  print_every: 100
  save_every: 100
  valid_every: 100
  nb_recons_loss_steps: null
  use_nll_loss: False
  inference_start: 640
  val_criterion: "error_rate"
