# General settings
general:
  seed: 2026
  classification: False
  train: True
  dataset: "comphy"
  data_path: "./data/comphy/"
  save_path: null

# Data hyperparameters
data:
  normalize: True
  sequence_length: 347
  data_dim: 3
  mini_res: 8        ## Factor to reduce the resolution of the video frames (1: original, 2: half, 3: third, etc.)

# Model hyperparameters
model:
  root_width_size: 10
  root_depth: 5
  root_activation: "sin"
  root_final_activation: null
  root_output_dim: 6
  positional_encoding: null
  init_state_layers: 0           ## Number of hidden layers in the MLP to generate the initial hidden state of the RNN   
  input_prev_data: False
  # conv_embedding: [256, 3, 1]
  conv_embedding: null
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: 0.5
  time_as_channel: False
  forcing_prob: 0.5
  noise_theta_init: null
  std_lower_bound: 1.0e-4

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-5
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 50
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference configurations
training:
  nb_epochs: 5000
  batch_size: 16
  autoregressive: False
  print_every: 10
  save_every: 10
  valid_every: 10
  stochastic: False
  val_criterion: "mse"
  nb_recons_loss_steps: null
  use_nll_loss: True
  inference_start: null     ## Should be None if non-autoregressive training.
  smooth_inference: True
