# Base configuration file

# General settings
general:
  seed: 2024
  classification: True
  train: True
  dataset: "uea"  # Options: mnist, cifar, lorentz, dynamics
  data_path: "./data/uea/processed/UEA/EigenWorms/"
  save_path: null

# Data hyperparameters (dependent on the dataset)
data:
  downsample_factor: 1
  resolution: [32, 32]         # For celebA
  traj_length: 1000
  normalize: False

# Model hyperparameters
model:
  root_width_size: 128
  root_depth: 1
  root_activation: "relu"
  root_final_activation: null     ## a, b, alpha, beta
  init_state_layers: 2        ## null to directly learn the initial state
  input_prev_data: False
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: False
  forcing_prob: 0.25
  noise_theta_init: null
  std_lower_bound: 1.0e-4

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-7
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference hyperparameters
training:
  nb_epochs: 100
  batch_size: 32
  autoregressive: False
  stochastic: False
  print_every: 1
  save_every: 1
  valid_every: 1
  val_criterion: "error_rate"
  checkpoint_every: 10
  nb_recons_loss_steps: null
  use_nll_loss: False
  inference_start: 100
