# General settings
general:
  seed: 2024
  classification: True
  train: True
  dataset: "uea"
  data_path: "./data/uea/processed/UEA/MotorImagery/"
  save_path: null

# Data hyperparameters
data:
  normalize: False

# Model hyperparameters
model:
  root_width_size: 32
  root_depth: 2
  root_activation: "relu"
  root_final_activation: null
  init_state_layers: 2
  input_prev_data: False
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: False
  forcing_prob: 0.25
  noise_theta_init: null
  std_lower_bound: 1.0e-4

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-6
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference configurations
training:
  nb_epochs: 100
  batch_size: 128
  autoregressive: False
  stochastic: False
  print_every: 10
  save_every: 10
  valid_every: 10
  val_criterion: "error_rate"
  nb_recons_loss_steps: null
  use_nll_loss: False
  inference_start: 100
  smooth_inference: True
