# General settings
general:
  seed: 2028
  classification: True
  train: True
  dataset: "mnist"
  data_path: "./data/"
  save_path: null

# Data hyperparameters
data:
  downsample_factor: 1

# Model hyperparameters
model:
  root_width_size: 32
  root_depth: 2
  root_activation: "relu"
  root_final_activation: null
  init_state_layers: null
  input_prev_data: False
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: False
  forcing_prob: 0.15
  noise_theta_init: null
  std_lower_bound: 5.0e-1

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-6
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 200
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 500

# Training/Inference configurations
training:
  nb_epochs: 480
  batch_size: 128
  autoregressive: False
  stochastic: False
  print_every: 10
  save_every: 10
  valid_every: 10
  val_criterion: "error_rate"
  nb_recons_loss_steps: 400
  use_nll_loss: True
  inference_start: 300
  smooth_inference: True
