# General settings
general:
  seed: 2028
  classification: False
  train: True
  dataset: "mnist"
  data_path: "./data/"
  save_path: null

# Data hyperparameters
data:
  downsample_factor: 2
  normalize: False
  positional_encoding: [6, 100]

# Model hyperparameters
model:
  root_width_size: 10
  root_depth: 5
  root_activation: "swish"
  root_final_activation: "tanh"
  init_state_layers: null
  input_prev_data: False
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: False
  forcing_prob: 0.15
  noise_theta_init: null
  std_lower_bound: 1.0e-2

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-5
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference configurations
training:
  nb_epochs: 100
  batch_size: 1280
  autoregressive: True
  print_every: 10
  save_every: 10
  valid_every: 10
  stochastic: False
  val_criterion: "mse"
  use_nll_loss: False
  smooth_inference: True
  nb_recons_loss_steps: null
  inference_start: 100
