# Base configuration file

# General settings
general:
  seed: 2024
  train: True
  dataset: "mass_spring_damper"  # Options: mnist, cifar, lorentz, dynamics
  data_path: "./data/dynamics/mass-spring-damper/"
  # save_path: "./runs/250404-175026-Test/"
  save_path: null

# Data hyperparameters (dependent on the dataset)
data:
  downsample_factor: 1
  resolution: [32, 32]         # For celebA
  traj_length: 1000

# Model hyperparameters
model:
  mlp_width_size: 48
  mlp_depth: 3
  activation: "swish"
  input_prev_data: False
  model_type: "lstm"
  nb_rnn_layers: 1
  weights_lim: null
  apply_dynamic_tanh: False
  time_as_channel: False
  forcing_prob: 0.15
  noise_theta_init: null
  std_lower_bound: 1.0e-4
  rnn_hidden_size: 2450          # For GRUs and LSTMs

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-5
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference hyperparameters
training:
  nb_epochs: 1500
  batch_size: 380
  print_every: 10
  checkpoint_every: 10
  nb_recons_loss_steps: null
  use_nll_loss: False
  inference_start: 100
