# General settings
general:
  seed: 2024
  train: True
  classification: False
  dataset: "lotka"
  data_path: "./data/dynamics/lotka/"
  save_path: null

# Data hyperparameters
data:
  traj_length: 1000
  normalize: True

# Model hyperparameters
model:
  root_width_size: 48
  root_depth: 3
  root_activation: "swish"
  root_final_activation: [1.0, 0.0, 1.0, 0.0]
  input_prev_data: False
  init_state_layers: null
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: False
  forcing_prob: 1.0
  noise_theta_init: null
  std_lower_bound: 1.0e-4

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-5
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference hyperparameters
training:
  nb_epochs: 1500
  batch_size: 1024
  print_every: 10
  save_every: 10
  valid_every: 10
  val_criterion: "mse"
  autoregressive: True
  stochastic: False
  nb_recons_loss_steps: null
  use_nll_loss: False
  inference_start: 256
  smooth_inference: True
