# General settings
general:
  seed: 2025
  classification: False
  train: True
  dataset: "arc_agi"
  data_path: "./data/arc_agi/"
  save_path: null

# Data hyperparameters
data:
  downsample_factor: 2
  normalize: False

# Model hyperparameters
model:
  root_width_size: 24
  root_depth: 3
  root_activation: "relu"
  root_final_activation: null
  init_state_layers: 2
  input_prev_data: False
  model_type: "ffnn"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: False
  forcing_prob: 0.15
  noise_theta_init: null
  std_lower_bound: 1.0e-4

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-5
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference configurations
training:
  nb_epochs: 20000
  batch_size: 5
  autoregressive: True
  print_every: 100
  save_every: 100
  valid_every: 100
  stochastic: False
  val_criterion: "mse"
  nb_recons_loss_steps: null
  use_nll_loss: False
  inference_start: 300
  smooth_inference: True
