# General settings
general:
  seed: 2028
  classification: True
  train: True
  dataset: "pathfinder"
  data_path: "./data/pathfinder/32/"
  save_path: null

# Data hyperparameters
data:
  resolution: [32, 32]
  normalize: True

# Model hyperparameters
model:
  mlp_width_size: 512
  mlp_depth: 1
  activation: "relu"
  init_state_layers: 2
  input_prev_data: False
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: null
  dynamic_tanh_init: null
  time_as_channel: False
  forcing_prob: 0.15
  noise_theta_init: null
  std_lower_bound: 5.0e-1

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-5
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference configurations
training:
  nb_epochs: 120
  batch_size: 920
  autoregressive: False
  stochastic: True
  print_every: 10
  save_every: 10
  valid_every: 10
  val_criterion: "error_rate"
  smooth_inference: True
  nb_recons_loss_steps: 400
  use_nll_loss: True
  inference_start: 300
