# General settings
general:
  seed: 2026
  classification: False
  train: True
  dataset: "traffic"
  data_path: "./data/traffic/"
  save_path: null

# Data hyperparameters
data:
  normalize: True
  sequence_length: 12
  data_dim: 510

# Model hyperparameters
model:
  root_width_size: 48
  root_depth: 1
  root_activation: "relu"
  root_final_activation: null
  root_output_dim: 170              ## If set, then careful with the NLL loss, and its splitting into means and stds.
  positional_encoding: [6, 10]     # Dimension of positional encoding, then denominator constant.
  positional_encoding: null
  init_state_layers: 2
  input_prev_data: False
  conv_embedding: [4080, 36, 0]         ## Convolutional embedding output size, then kernel size, and whether causal or not
  # conv_embedding: null
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: False
  forcing_prob: 0.5
  noise_theta_init: null
  std_lower_bound: 1.0e-4

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-5
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference configurations
training:
  nb_epochs: 3000
  batch_size: 128
  autoregressive: False
  print_every: 100
  save_every: 100
  valid_every: 100
  stochastic: False
  val_criterion: "mae"
  nb_recons_loss_steps: null
  use_nll_loss: False
  inference_start: null     ## Should be None if non-autoregressive training.
  smooth_inference: True
