# General settings
general:
  seed: 2028
  train: True
  dataset: "sine"
  data_path: "./data/dynamics/sine/medium/"
  save_path: null
  classification: False

# Data hyperparameters
data:
  normalize: False

# Model hyperparameters
model:
  root_width_size: 48
  root_depth: 3
  root_activation: "swish"
  root_final_activation: null
  init_state_layers: 2
  input_prev_data: False
  model_type: "wsm"
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: False
  forcing_prob: 0.25
  noise_theta_init: null
  std_lower_bound: 1.0e-4

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-5
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference configurations
training:
  nb_epochs: 1000
  batch_size: 10000
  autoregressive: True
  stochastic: False
  print_every: 100
  save_every: 100
  valid_every: 100
  val_criterion: "mse"
  nb_recons_loss_steps: null
  use_nll_loss: False
  inference_start: 1
  smooth_inference: True
