# General settings
general:
  seed: 2024
  classification: False
  train: True
  dataset: "electricity"
  data_path: "./data/dynamics/electricity/m1/"
  save_path: null

# Data hyperparameters
data:
  normalize: True

# Model hyperparameters
model:
  root_width_size: 148
  root_depth: 1
  root_activation: "relu"
  root_final_activation: null
  input_prev_data: False
  model_type: "wsm"
  init_state_layers: 2
  nb_rnn_layers: 1
  weights_lim: null
  time_as_channel: True
  forcing_prob: 0.25
  noise_theta_init: null
  std_lower_bound: 1.0e-4

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-4
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 10

# Training/Inference configurations
training:
  nb_epochs: 250
  batch_size: 3600
  autoregressive: True
  stochastic: True
  print_every: 10
  save_every: 10
  valid_every: 10
  val_criterion: "mse"
  nb_recons_loss_steps: null
  use_nll_loss: True
  inference_start: 96
  smooth_inference: False
