# Base configuration file

# General settings
general:
  seed: 2028
  train: True
  classification: False
  dataset: "mnist"  # Options: mnist, cifar, lorentz, dynamics
  data_path: "./data/"
  # save_path: "./runs/250404-175026-Test/"
  save_path: null

# Data hyperparameters (dependent on the dataset)
data:
  downsample_factor: 1
  resolution: [32, 32]         # For celebA
  traj_length: 1000

# Model hyperparameters
model:
  root_width_size: 24
  root_depth: 3
  root_activation: "relu"
  root_final_activation: "tanh"
  input_prev_data: False
  model_type: "lstm"
  nb_rnn_layers: 1
  weights_lim: 5.0e-1
  apply_dynamic_tanh: True
  time_as_channel: False
  forcing_prob: 0.15
  noise_theta_init: null
  std_lower_bound: 5.0e-1
  rnn_hidden_size: 650

# Optimizer hyperparameters
optimizer:
  init_lr: 1.0e-4
  gradients_lim: 1.0e-7
  on_plateau:
    factor: 0.5
    min_scale: 1.0e-2
    patience: 20
    cooldown: 0
    rtol: 1.0e-4
    accum_size: 50

# Training/Inference hyperparameters
training:
  nb_epochs: 500
  batch_size: 128
  print_every: 10
  checkpoint_every: 10
  nb_recons_loss_steps: 400
  use_nll_loss: True
  inference_start: 300
  smooth_inference: True
  stochastic: False
  val_criterion: "mse"
  autoregressive: True
  valid_every: 10
  save_every: 10
